ALTER TABLE submissions
    ALTER created_at SET DATA TYPE TIMESTAMP WITH TIME ZONE,
    ALTER updated_at SET DATA TYPE TIMESTAMP WITH TIME ZONE,
    ALTER submitted_at SET DATA TYPE TIMESTAMP WITH TIME ZONE
;

ALTER TABLE user_files
    ALTER created_at SET DATA TYPE TIMESTAMP WITH TIME ZONE;
