name: Create Pre-Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        type: string
        required: true
      refToRelease:
        description: 'Ref to release (branch, sha, tag, etc)'
        type: string
        required: true
        default: 'main'

jobs:
  run-tests:
    name: Run tests
    uses: ./.github/workflows/run-tests.yml
  create-pre-release:
    name: Create Pre-Release
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0
        with:
          ref: ${{ inputs.refToRelease }}
      - name: Tag Version
        env:
          VERSION: ${{inputs.version}}
        run: |
          echo Creating pre-release version: $VERSION
          git config --local user.email "platforms-robot@codeforamerica.org"
          git config --local user.name "CfA Platforms Robot"
          git tag -a $VERSION -m "Pre-release version $VERSION"
          git push origin $VERSION
      - name: Draft Release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3
        with:
          tag_name: ${{inputs.version}}
          generate_release_notes: true
          body: |
            FILL IN DETAILS ABOUT THIS RELEASE!
          draft: true
          prerelease: true
