name: Create Pre-Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        type: string
        required: true
jobs:
  run-tests:
    uses: ./.github/workflows/run-tests.yml
  whatever:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pre-Release
        run: echo ${{inputs.version}}
