on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        type: string
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Noop
        run: echo ${{ inputs.version }}